language: csharp
solution: cloudscribe.MetaWeblog.sln
sudo: false
dist: xenial
mono: none
dotnet: 3.0.100
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux

script:
  - dotnet restore
  - dotnet build -c Release
  # - dotnet test -c Release ./test/cloudscribe.MetaWeblog.Tests/cloudscribe.MetaWeblog.Tests.csproj
